# Generated by Django 4.2 on 2023-05-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_uploadedfile_uploaded_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZeroWatermark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="zero_watermarks/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
